#
# .gitea/gitea-ci.yaml
#

name: Build And Test
run-name: ${{ gitea.actor }} is runs ci pipeline
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v4
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."images.physi.uni-heidelberg.de"]
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: images.physi.uni-heidelberg.de/pibackup
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v6
        with:
          context: ./Docker
          file: ./Dockerfile
          push: true
          #tags: "images.physi.uni-heidelberg.de/pibackup,images.physi.uni-heidelberg.de/pibackup:latest"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}